name: Lint/Test Conda
on: [push]

jobs:
  test:
    name: (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        # python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
        python-version: [2.7]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pip
          pip install --upgrade setuptools
          pip install -r dev_requirements.txt
          pip install -e .

      - name: Lint with flake8
        shell: bash -l {0}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          py.test --cov=./
